project:
  type: website
  output-dir: _site

website:
  title: "Tim's Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Posts
        href: posts/index.qmd
format:
  html:
    theme: cosmo
    toc: true
